title: Designing the Data Science Classroom
description: Materials for the Designing the Data Science Classroom workshop at [rstudio::conf(2020)](rstd.io/conf)
logo: logo/logo.gif
show_downloads: true
theme: jekyll-theme-minimal
plugins:
  - jemoji